import type { Handle } from '@sveltejs/kit';

/**
 * Defensive headers for every response the frontend serves. The Content-Security-Policy is
 * generated by SvelteKit (see `kit.csp` in `svelte.config.js`); HSTS is set by the TLS-terminating
 * reverse proxy. Values that overlap with the proxy's headers are kept identical so that the
 * proxy overwriting them changes nothing.
 */
export const securityHeaders: Record<string, string> = {
	'X-Content-Type-Options': 'nosniff',
	'X-Frame-Options': 'SAMEORIGIN',
	'Referrer-Policy': 'strict-origin-when-cross-origin',
	'Permissions-Policy': 'camera=(self), microphone=(), geolocation=(), payment=(), usb=()',
	'Cross-Origin-Opener-Policy': 'same-origin'
};

export const handle: Handle = async ({ event, resolve }) => {
	const response = await resolve(event);
	for (const [name, value] of Object.entries(securityHeaders)) {
		if (!response.headers.has(name)) response.headers.set(name, value);
	}
	return response;
};
